-- SEND_TXN_OWNER.SEND_TRANSACTIONS definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE SEND_TXN_OWNER.SEND_TRANSACTIONS;

CREATE TABLE SEND_TXN_OWNER.SEND_TRANSACTIONS (
                                                  TRAN_ID VARCHAR2(50),
                                                  TRAN_INIT_ID VARCHAR2(50),
                                                  ORIG_INST_ID VARCHAR2(50),
                                                  ORIG_INST_NAM VARCHAR2(250),
                                                  TRANFR_ACPT_NAM VARCHAR2(250),
                                                  TRANFR_ACPT_ID VARCHAR2(40),
                                                  TRAN_CRTE_DT TIMESTAMP,
                                                  TRAN_TYPE VARCHAR2(10),
                                                  CUST_REF_NUM VARCHAR2(100),
                                                  CUR_STAT VARCHAR2(20),
                                                  ORIG_STAT VARCHAR2(20),
                                                  USE_CASE VARCHAR2(3),
                                                  MSG_TYPE VARCHAR2(10),
                                                  REF_ID VARCHAR2(40),
                                                  SW_SER_NUM VARCHAR2(20),
                                                  BNKNT_REF_NUM VARCHAR2(1000),
                                                  SEND_ACCT VARCHAR2(100),
                                                  RECIP_ACCT VARCHAR2(100),
                                                  TRAN_AMT NUMBER(22,0),
                                                  TRAN_CURR VARCHAR2(3),
                                                  ERR_CD VARCHAR2(25),
                                                  FUND_AVAIL VARCHAR2(30),
                                                  CORLTN_ID VARCHAR2(40),
                                                  CRTE_TS TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE ,
                                                  CRTE_USER_NAM VARCHAR2(20),
                                                  UPDT_TS TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE,
                                                  UPDT_USER_NAM VARCHAR2(20),
                                                  RPLCTN_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP  ,
                                                  NTWRK_CD VARCHAR2(40),
                                                  TRAN_INIT_NAM VARCHAR2(250),
                                                  NTWRK_RESP_CD VARCHAR2(30),
                                                  NAM_STAT VARCHAR2(20),
                                                  CVC_STAT VARCHAR2(20),
                                                  CVC_RESP_CD VARCHAR2(5),
                                                  ACCT_NUM VARCHAR2(50),
                                                  ACCT_TYPE VARCHAR2(20),
                                                  ACCT_HOLD_NAM VARCHAR2(250),
                                                  ERR_CD_DESC VARCHAR2(500),
                                                  NON_FIN_TXN NUMBER(1,0) DEFAULT 0 ,
                                                  NTWRK_RESP_CD_DESC VARCHAR2(500),
                                                  TRACE_ID VARCHAR2(50),
                                                  ORIG_CNTRY VARCHAR2(20),
                                                  SEND_ERR_CD VARCHAR2(25),
                                                  RECIP_ERR_CD VARCHAR2(25),
                                                  SEND_ELIG NUMBER(1,0),
                                                  RECIP_ELIG NUMBER(1,0),
                                                  ADDR_STAT VARCHAR2(20),
                                                  POST_CD_STAT VARCHAR2(20),
                                                  AVS_RESP_CD VARCHAR2(5),
                                                  TLID VARCHAR2(22),
                                                  CONSTRAINT SEND_TRANSACTIONS_PK PRIMARY KEY (TRAN_ID),
                                                  CONSTRAINT SYS_C0054162 CHECK ("TRAN_CRTE_DT" IS NOT NULL),
                                                  CONSTRAINT SYS_C0054163 CHECK ("TRAN_TYPE" IS NOT NULL),
                                                  CONSTRAINT SYS_C0054164 CHECK ("CUR_STAT" IS NOT NULL),
                                                  CONSTRAINT SYS_C0054165 CHECK ("ORIG_STAT" IS NOT NULL),
                                                  CONSTRAINT SYS_C0054747 CHECK ("RPLCTN_UPDT_TS" IS NOT NULL),
                                                  CONSTRAINT SYS_C0084699 CHECK ("NON_FIN_TXN" IS NOT NULL)
);
CREATE INDEX IDX_SEND_TXN_ADDR_STAT ON SEND_TXN_OWNER.SEND_TRANSACTIONS (ADDR_STAT);
CREATE INDEX IDX_SEND_TXN_CVC_STAT ON SEND_TXN_OWNER.SEND_TRANSACTIONS (CVC_STAT);
CREATE INDEX IDX_SEND_TXN_NAM_STAT ON SEND_TXN_OWNER.SEND_TRANSACTIONS (NAM_STAT);
CREATE INDEX IDX_SEND_TXN_POST_CD_STAT ON SEND_TXN_OWNER.SEND_TRANSACTIONS (POST_CD_STAT);
CREATE INDEX IDX_SEND_TXN_RECIP_ELIG ON SEND_TXN_OWNER.SEND_TRANSACTIONS (RECIP_ELIG);
CREATE INDEX IDX_SEND_TXN_SEND_ELIG ON SEND_TXN_OWNER.SEND_TRANSACTIONS (SEND_ELIG);
CREATE INDEX IDX_SEND_TXN_TLID ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TLID);
CREATE INDEX IDX_SEND_TXN_TRAN_TYPE ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TRAN_TYPE);
CREATE UNIQUE INDEX SEND_TRANSACTIONS_PK ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TRAN_ID);
CREATE INDEX SEND_TXN_IDX10 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (NTWRK_CD);
CREATE INDEX SEND_TXN_INDX01 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TRAN_INIT_ID);
CREATE INDEX SEND_TXN_INDX02 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (ORIG_INST_NAM);
CREATE INDEX SEND_TXN_INDX03 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (REF_ID);
CREATE INDEX SEND_TXN_INDX04 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TRAN_CRTE_DT);
CREATE INDEX SEND_TXN_INDX05 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (TRANFR_ACPT_NAM);
CREATE INDEX SEND_TXN_INDX06 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (CUST_REF_NUM);
CREATE INDEX SEND_TXN_INDX07 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (CUR_STAT);
CREATE INDEX SEND_TXN_INDX08 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (ORIG_STAT);
CREATE INDEX SEND_TXN_INDX09 ON SEND_TXN_OWNER.SEND_TRANSACTIONS (USE_CASE);


-- SEND_TXN_OWNER.SEND_TRAN_DTL definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE SEND_TXN_OWNER.SEND_TRAN_DTL;

CREATE TABLE SEND_TXN_OWNER.SEND_TRAN_DTL (
                                              TRAN_ID VARCHAR2(50),
                                              PAYMT_REF VARCHAR2(50),
                                              UNQ_TRAN_REF VARCHAR2(50),
                                              ACQ_CNTRY_NAM VARCHAR2(60),
                                              ACQ_ICA NUMBER(38,0),
                                              FUND_SRC VARCHAR2(50),
                                              ICHG_RATE_DSGN VARCHAR2(50),
                                              MERCH_CAT_CD VARCHAR2(50),
                                              PAYMT_TYPE VARCHAR2(50),
                                              POINT_SERV_INTRCTN VARCHAR2(60),
                                              TRAN_PRPS VARCHAR2(50),
                                              TRAN_SETL_AMT VARCHAR2(50),
                                              BNC_GTWY_RQST CLOB,
                                              BNC_GTWY_RESP CLOB,
                                              ORIG_RQST_PYLD CLOB,
                                              ORIG_RESP_PYLD CLOB,
                                              TRANFR_ACPT_ID VARCHAR2(100),
                                              TRANFR_ACPT_NAM VARCHAR2(250),
                                              MC_ASSGN_MERCH VARCHAR2(60),
                                              PAYMT_FACILTR_ID VARCHAR2(50),
                                              SUB_MERCH_ID VARCHAR2(50),
                                              TRANFR_TRML_ID VARCHAR2(60),
                                              TRANFR_ACPT_ST_LINE1 VARCHAR2(250),
                                              TRANFR_ACPT_ST_LINE2 VARCHAR2(250),
                                              TRANFR_ACPT_CITY VARCHAR2(60),
                                              TRANFR_ACPT_ST VARCHAR2(60),
                                              TRANFR_ACPT_CNTRY_NAM VARCHAR2(60),
                                              TRANFR_ACPT_POST_CD VARCHAR2(60),
                                              CRTE_TS TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE ,
                                              CRTE_USER_NAM VARCHAR2(20),
                                              UPDT_TS TIMESTAMP WITH TIME ZONE,
                                              UPDT_USER_NAM VARCHAR2(20),
                                              EVENT_ID VARCHAR2(40),
                                              EVENT_TS TIMESTAMP WITH TIME ZONE,
                                              EVENT_CORLTN_ID VARCHAR2(40),
                                              MSG_VERSION VARCHAR2(10),
                                              TRAN_CRTE_DT TIMESTAMP,
                                              RPLCTN_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP  ,
                                              TRAN_TYPE_IND_CD VARCHAR2(5),
                                              REGULATED_RATE_TYPE_CD VARCHAR2(5),
                                              CVC_RESP_DESC VARCHAR2(500),
                                              PROC_ID VARCHAR2(20),
                                              ACQ_IDEN_CD VARCHAR2(20),
                                              TRANFR_ACPT_MPG_ID VARCHAR2(20),
                                              TRANFR_ACPT_MERCH_VALUE VARCHAR2(20),
                                              ENHANC_RESP NUMBER(1,0),
                                              BRAND VARCHAR2(20),
                                              ACCPT_BRAND VARCHAR2(20),
                                              PROD_TYPE VARCHAR2(20),
                                              ACCT_URI VARCHAR2(60),
                                              INST_NAM VARCHAR2(100),
                                              INST_CNTRY_NAM VARCHAR2(20),
                                              SEND_ERR_CD_DESC VARCHAR2(500),
                                              RECIP_ERR_CD_DESC VARCHAR2(500),
                                              ACCT_STMT_CURR VARCHAR2(3),
                                              AVS_RESP_CD_DESC VARCHAR2(500),
                                              TRAN_TYPE_CD VARCHAR2(2),
                                              TRAN_TYPE_DESC VARCHAR2(50),
                                              SYS_TRACE_AUD_NUM VARCHAR2(6),
                                              AUTH_ID_RESP_CD VARCHAR2(6),
                                              OPRT_ENV VARCHAR2(50),
                                              TRAN_LOC_TS TIMESTAMP,
                                              LOC_DT_TXT VARCHAR2(50),
                                              CONSTRAINT SEND_TRAN_DTL_PK PRIMARY KEY (TRAN_ID),
                                              CONSTRAINT SYS_C0054169 CHECK ("TRAN_CRTE_DT" IS NOT NULL),
                                              CONSTRAINT SYS_C0054745 CHECK ("RPLCTN_UPDT_TS" IS NOT NULL),
                                              CONSTRAINT SEND_TRAN_DTL_FK FOREIGN KEY (TRAN_ID) REFERENCES SEND_TXN_OWNER.SEND_TRANSACTIONS(TRAN_ID)
);
CREATE INDEX IDX_SEND_TRAN_DTL_RESP_PYLD_TEXT ON SEND_TXN_OWNER.SEND_TRAN_DTL (ORIG_RESP_PYLD);
CREATE UNIQUE INDEX SEND_TRAN_DTL_PK ON SEND_TXN_OWNER.SEND_TRAN_DTL (TRAN_ID);


-- SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL;

CREATE TABLE SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL (
                                                   ID VARCHAR2(50),
                                                   TRAN_ID VARCHAR2(50),
                                                   ADDR_TYPE VARCHAR2(50),
                                                   ST_LINE1 VARCHAR2(250),
                                                   ST_LINE2 VARCHAR2(250),
                                                   CITY VARCHAR2(60),
                                                   ST VARCHAR2(60),
                                                   CNTRY_NAM VARCHAR2(60),
                                                   POST_CD VARCHAR2(60),
                                                   ADDR_STAT VARCHAR2(20),
                                                   POST_CD_STAT VARCHAR2(20),
                                                   CRTE_TS TIMESTAMP DEFAULT SYSTIMESTAMP,
                                                   UPDT_TS TIMESTAMP,
                                                   CRTE_USER_NAM VARCHAR2(20),
                                                   UPDT_USER_NAM VARCHAR2(20),
                                                   RPLCTN_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP ,
                                                   CONSTRAINT SEND_TRAN_ADDR_DTL_PK PRIMARY KEY (ID),
                                                   CONSTRAINT SYS_C00195201 CHECK ("RPLCTN_UPDT_TS" IS NOT NULL),
                                                   CONSTRAINT SEND_TRAN_ADDR_DTL_FK1 FOREIGN KEY (TRAN_ID) REFERENCES SEND_TXN_OWNER.SEND_TRANSACTIONS(TRAN_ID)
);
CREATE INDEX IDX_SEND_TRAN_ADDR_DTL_ADDR_STAT ON SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL (ADDR_STAT);
CREATE INDEX IDX_SEND_TRAN_ADDR_DTL_POST_CD_STAT ON SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL (POST_CD_STAT);
CREATE UNIQUE INDEX SEND_TRAN_ADDR_DTL_PK ON SEND_TXN_OWNER.SEND_TRAN_ADDR_DTL (ID);


-- SEND_TXN_OWNER.SEND_TRAN_CLRG_SETLMT definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE SEND_TXN_OWNER.SEND_TRAN_CLRG_SETLMT;

CREATE TABLE SEND_TXN_OWNER.SEND_TRAN_CLRG_SETLMT (
                                                      TRAN_ID VARCHAR2(50),
                                                      CLRG_ST VARCHAR2(50),
                                                      CLRG_DT_TS TIMESTAMP,
                                                      ACQ_ICA_REF_TXT VARCHAR2(250),
                                                      RATE_TYPE_IND VARCHAR2(60),
                                                      MSG_RSN_CD VARCHAR2(60),
                                                      MSG_RSN_DESC VARCHAR2(60),
                                                      ICHG_RATE_DSGN_CD VARCHAR2(60),
                                                      ICHG_FEE VARCHAR2(100),
                                                      BUSN_SRV_AGMT VARCHAR2(100),
                                                      CRTE_TS TIMESTAMP DEFAULT SYSTIMESTAMP ,
                                                      UPDT_TS TIMESTAMP,
                                                      CRTE_USER_NAM VARCHAR2(20),
                                                      UPDT_USER_NAM VARCHAR2(20),
                                                      RPLCTN_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP ,
                                                      SETL_DT DATE,
                                                      SETL_AMT NUMBER,
                                                      SETL_CURR_CD VARCHAR2(3),
                                                      SETL_SERV_ID VARCHAR2(11),
                                                      SETL_ICA VARCHAR2(11),
                                                      TRAN_FILE_ID VARCHAR2(25),
                                                      CONSTRAINT SEND_TRAN_CLRG_SETLMT_PK PRIMARY KEY (TRAN_ID),
                                                      CONSTRAINT SYS_C00195575 CHECK ("TRAN_ID" IS NOT NULL),
                                                      CONSTRAINT SYS_C00195576 CHECK ("CLRG_ST" IS NOT NULL),
                                                      CONSTRAINT SYS_C00195577 CHECK ("CLRG_DT_TS" IS NOT NULL),
                                                      CONSTRAINT SYS_C00195578 CHECK ("CRTE_TS" IS NOT NULL),
                                                      CONSTRAINT SYS_C00195579 CHECK ("UPDT_TS" IS NOT NULL),
                                                      CONSTRAINT SYS_C00195580 CHECK ("RPLCTN_UPDT_TS" IS NOT NULL),
                                                      CONSTRAINT SEND_TRAN_CLRG_SETLMT_FK1 FOREIGN KEY (TRAN_ID) REFERENCES SEND_TXN_OWNER.SEND_TRANSACTIONS(TRAN_ID)
);
CREATE INDEX IDX_SEND_TRAN_CLRG_SETLMT_CLRG_ST ON SEND_TXN_OWNER.SEND_TRAN_CLRG_SETLMT (CLRG_ST);
CREATE UNIQUE INDEX SEND_TRAN_CLRG_SETLMT_PK ON SEND_TXN_OWNER.SEND_TRAN_CLRG_SETLMT (TRAN_ID);

-- SEND_TXN_OWNER.SEND_RECIP_DTL definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE SEND_TXN_OWNER.SEND_RECIP_DTL;

CREATE TABLE SEND_TXN_OWNER.SEND_RECIP_DTL (
                                               TRAN_ID VARCHAR2(50),
                                               SEND_FIRST_NAM VARCHAR2(80),
                                               SEND_MID_NAM VARCHAR2(80),
                                               SEND_LST_NAM VARCHAR2(80),
                                               SEND_PHN VARCHAR2(20),
                                               SEND_EMAIL VARCHAR2(254),
                                               SEND_DOB DATE,
                                               SEND_NATL VARCHAR2(60),
                                               SEND_BIRTH_CNTRY_NAM VARCHAR2(20),
                                               SEND_ACCT_NUM VARCHAR2(50),
                                               SEND_ACCT_URI VARCHAR2(60),
                                               SEND_GOVT_ID_URI CLOB,
                                               SEND_ACCT_NUM_TYPE VARCHAR2(10),
                                               SEND_CARD_NUM VARCHAR2(50),
                                               SEND_CARD_EXPIR_DT VARCHAR2(10),
                                               SEND_ST_LINE1 VARCHAR2(250),
                                               SEND_ST_LINE2 VARCHAR2(250),
                                               SEND_CITY VARCHAR2(50),
                                               SEND_ST VARCHAR2(10),
                                               SEND_CNTRY_NAM VARCHAR2(20),
                                               SEND_POST_CD VARCHAR2(10),
                                               RECIP_FIRST_NAM VARCHAR2(80),
                                               RECIP_MID_NAM VARCHAR2(80),
                                               RECIP_LST_NAM VARCHAR2(80),
                                               RECIP_PHN VARCHAR2(20),
                                               RECIP_EMAIL VARCHAR2(254),
                                               RECIP_DOB DATE,
                                               RECIP_NATL VARCHAR2(3),
                                               RECIP_BIRTH_CNTRY_NAM VARCHAR2(20),
                                               RECIP_ACCT_NUM VARCHAR2(50),
                                               RECIP_ACCT_URI VARCHAR2(60),
                                               RECIP_GOVT_ID_URI CLOB,
                                               RECIP_ACCT_NUM_TYPE VARCHAR2(10),
                                               RECIP_CARD_NUM VARCHAR2(50),
                                               RECIP_CARD_EXPIR_DT VARCHAR2(10),
                                               RECIP_ST_LINE1 VARCHAR2(250),
                                               RECIP_ST_LINE2 VARCHAR2(250),
                                               RECIP_CITY VARCHAR2(50),
                                               RECIP_ST VARCHAR2(10),
                                               RECIP_CNTRY_NAM VARCHAR2(20),
                                               RECIP_POST_CD VARCHAR2(10),
                                               CRTE_TS TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE ,
                                               CRTE_USER_NAM VARCHAR2(20),
                                               UPDT_TS TIMESTAMP WITH TIME ZONE,
                                               UPDT_USER_NAM VARCHAR2(20),
                                               TRAN_CRTE_DT TIMESTAMP,
                                               RPLCTN_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP  ,
                                               RCVR_SRT_CD VARCHAR2(6),
                                               SEND_SRT_CD VARCHAR2(6),
                                               CONSTRAINT SEND_RECIP_DTL_PK PRIMARY KEY (TRAN_ID),
                                               CONSTRAINT SYS_C0054173 CHECK ("TRAN_CRTE_DT" IS NOT NULL),
                                               CONSTRAINT SYS_C0054746 CHECK ("RPLCTN_UPDT_TS" IS NOT NULL),
                                               CONSTRAINT SEND_RECIP_DTL_FK FOREIGN KEY (TRAN_ID) REFERENCES SEND_TXN_OWNER.SEND_TRANSACTIONS(TRAN_ID)
);
CREATE UNIQUE INDEX SEND_RECIP_DTL_PK ON SEND_TXN_OWNER.SEND_RECIP_DTL (TRAN_ID);
CREATE INDEX SEND_RECIP_INDX01 ON SEND_TXN_OWNER.SEND_RECIP_DTL (SEND_EMAIL);
CREATE INDEX SEND_RECIP_INDX02 ON SEND_TXN_OWNER.SEND_RECIP_DTL (SEND_PHN);
CREATE INDEX SEND_RECIP_INDX03 ON SEND_TXN_OWNER.SEND_RECIP_DTL (SEND_ACCT_URI);