package com.poc.transactions_consumer_canonical.repository;

import com.poc.transactions_consumer_canonical.metadata.ColumnMetadata;
import com.poc.transactions_consumer_canonical.metadata.MetadataRegistry;
import com.poc.transactions_consumer_canonical.metadata.TableMetadata;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Generic CRUD over any {@link TableMetadata}-described table.
 * Payloads are {@link Map}s keyed by {@code jsonName} from the YAML metadata.
 * <p>
 * SQL is generated by {@link SqlBuilder} and cached. Parameter binding iterates
 * the metadata columns and applies the per-column {@link ValueConverter} + JDBC type.
 */
@Slf4j
@Repository
@RequiredArgsConstructor
public class GenericTableRepository {

    private final NamedParameterJdbcTemplate jdbc;
    private final MetadataRegistry registry;
    private final SqlBuilder sqlBuilder;
    private final Converters converters;

    // ──────────────────────────────────────────────────────────
    // Write
    // ──────────────────────────────────────────────────────────

    public void upsert(String tableOrAlias, Map<String, Object> payload) {
        TableMetadata t = registry.require(tableOrAlias);
        String sql = sqlBuilder.buildMerge(t);
        MapSqlParameterSource params = buildParams(t, payload);
        log.debug("MERGE {} pk={}", t.getName(), payload.get(t.pkColumn().getJsonName()));
        jdbc.update(sql, params);
    }

    public int[] mergeAll(String tableOrAlias, List<Map<String, Object>> rows) {
        TableMetadata t = registry.require(tableOrAlias);
        if (rows == null || rows.isEmpty()) return new int[0];
        String sql = sqlBuilder.buildMerge(t);
        SqlParameterSource[] batch = rows.stream()
                .map(r -> (SqlParameterSource) buildParams(t, r))
                .toArray(SqlParameterSource[]::new);
        log.debug("MERGE {} batch size={}", t.getName(), rows.size());
        return jdbc.batchUpdate(sql, batch);
    }

    // ──────────────────────────────────────────────────────────
    // Read
    // ──────────────────────────────────────────────────────────

    public Optional<Map<String, Object>> findByPk(String tableOrAlias, Object pkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        String pkJson = t.pkColumn().getJsonName();
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByPk(t),
                    new MapSqlParameterSource(pkJson, pkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    public Optional<Map<String, Object>> findByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByFk(t, fkDbColumn),
                    new MapSqlParameterSource("fkValue", fkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    public List<Map<String, Object>> findAllByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.query(
                sqlBuilder.buildSelectByFk(t, fkDbColumn),
                new MapSqlParameterSource("fkValue", fkValue),
                new GenericRowMapper(t, converters));
    }

    public List<Map<String, Object>> findPage(String tableOrAlias, int offset, int size) {
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.query(
                sqlBuilder.buildSelectPage(t),
                new MapSqlParameterSource("offset", offset).addValue("size", size),
                new GenericRowMapper(t, converters));
    }

    public long count(String tableOrAlias) {
        TableMetadata t = registry.require(tableOrAlias);
        Long n = jdbc.queryForObject(sqlBuilder.buildCount(t), new MapSqlParameterSource(), Long.class);
        return n == null ? 0L : n;
    }

    // ──────────────────────────────────────────────────────────
    // Delete
    // ──────────────────────────────────────────────────────────

    public boolean deleteByPk(String tableOrAlias, Object pkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        String pkJson = t.pkColumn().getJsonName();
        return jdbc.update(sqlBuilder.buildDeleteByPk(t),
                new MapSqlParameterSource(pkJson, pkValue)) > 0;
    }

    public int deleteByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.update(sqlBuilder.buildDeleteByFk(t, fkDbColumn),
                new MapSqlParameterSource("fkValue", fkValue));
    }

    public int deleteByFkNotIn(String tableOrAlias, String fkDbColumn,
                               Object fkValue, List<?> keepPkValues) {
        if (keepPkValues == null || keepPkValues.isEmpty()) {
            return deleteByFk(tableOrAlias, fkDbColumn, fkValue);
        }
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.update(sqlBuilder.buildDeleteByFkNotIn(t, fkDbColumn),
                new MapSqlParameterSource("fkValue", fkValue).addValue("keepIds", keepPkValues));
    }

    // ──────────────────────────────────────────────────────────
    // Internal — parameter binding
    // ──────────────────────────────────────────────────────────

    private MapSqlParameterSource buildParams(TableMetadata t, Map<String, Object> payload) {
        MapSqlParameterSource params = new MapSqlParameterSource();
        for (ColumnMetadata col : t.getColumns()) {
            if (col.isAudit())   continue; // SYSTIMESTAMP in SQL, never bound
            if (col.isReadOnly()) continue;
            String key = col.getJsonName();
            if (key == null) continue;
            Object raw = payload.get(key);
            Object jdbcValue = converters.forName(col.converterName()).toJdbc(raw, col);
            params.addValue(key, jdbcValue, col.jdbcType());
        }
        return params;
    }
}
