package com.poc.transactions_consumer_canonical.repository;

import com.poc.transactions_consumer_canonical.metadata.MetadataRegistry;
import com.poc.transactions_consumer_canonical.metadata.TableMetadata;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Read-only generic CRUD over any {@link TableMetadata}-described table.
 * Payloads returned are {@link Map}s keyed by {@code jsonName} from the YAML metadata.
 * <p>
 * SQL is generated by {@link SqlBuilder} and cached. Only the read paths used by
 * the v2 REST surface are exposed here — writes flow through the Kafka canonical
 * pipeline and the typed repositories.
 */
@Slf4j
@Repository
@RequiredArgsConstructor
public class GenericTableRepository {

    private static final String FK_VALUE_PARAM = "fkValue";

    private final NamedParameterJdbcTemplate jdbc;
    private final MetadataRegistry registry;
    private final SqlBuilder sqlBuilder;
    private final Converters converters;

    public Optional<Map<String, Object>> findByPk(String tableOrAlias, Object pkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        String pkJson = t.pkColumn().getJsonName();
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByPk(t),
                    new MapSqlParameterSource(pkJson, pkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException _) {
            return Optional.empty();
        }
    }

    public Optional<Map<String, Object>> findByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByFk(t, fkDbColumn),
                    new MapSqlParameterSource(FK_VALUE_PARAM, fkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException _) {
            return Optional.empty();
        }
    }

    public List<Map<String, Object>> findAllByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.query(
                sqlBuilder.buildSelectByFk(t, fkDbColumn),
                new MapSqlParameterSource(FK_VALUE_PARAM, fkValue),
                new GenericRowMapper(t, converters));
    }
}
