package com.poc.transactions_consumer_canonical.repository;

import com.poc.transactions_consumer_canonical.metadata.ColumnMetadata;
import com.poc.transactions_consumer_canonical.metadata.MetadataRegistry;
import com.poc.transactions_consumer_canonical.metadata.TableMetadata;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Generic CRUD over any {@link TableMetadata}-described table.
 * Payloads are {@link Map}s keyed by {@code jsonName} from the YAML metadata.
 * <p>
 * SQL is generated by {@link SqlBuilder} and cached. Exposes the read paths used
 * by the v2 REST surface plus {@link #upsert(String, Map)} for the Kafka CLEARING
 * pipeline (the 5th-table-only write path).
 */
@Slf4j
@Repository
@RequiredArgsConstructor
public class GenericTableRepository {

    private static final String FK_VALUE_PARAM = "fkValue";

    private final NamedParameterJdbcTemplate jdbc;
    private final MetadataRegistry registry;
    private final SqlBuilder sqlBuilder;
    private final Converters converters;

    public void upsert(String tableOrAlias, Map<String, Object> payload) {
        TableMetadata t = registry.require(tableOrAlias);
        String sql = sqlBuilder.buildMerge(t);
        MapSqlParameterSource params = buildParams(t, payload);
        log.debug("MERGE {} pk={}", t.getName(), payload.get(t.pkColumn().getJsonName()));
        jdbc.update(sql, params);
    }

    private MapSqlParameterSource buildParams(TableMetadata t, Map<String, Object> payload) {
        MapSqlParameterSource params = new MapSqlParameterSource();
        for (ColumnMetadata col : t.getColumns()) {
            if (col.isAudit() || col.isReadOnly() || col.getJsonName() == null) continue;
            String key = col.getJsonName();
            Object raw = payload.get(key);
            Object jdbcValue = converters.forName(col.converterName()).toJdbc(raw, col);
            params.addValue(key, jdbcValue, col.jdbcType());
        }
        return params;
    }

    public Optional<Map<String, Object>> findByPk(String tableOrAlias, Object pkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        String pkJson = t.pkColumn().getJsonName();
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByPk(t),
                    new MapSqlParameterSource(pkJson, pkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException _) {
            return Optional.empty();
        }
    }

    public Optional<Map<String, Object>> findByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        try {
            return Optional.ofNullable(jdbc.queryForObject(
                    sqlBuilder.buildSelectByFk(t, fkDbColumn),
                    new MapSqlParameterSource(FK_VALUE_PARAM, fkValue),
                    new GenericRowMapper(t, converters)));
        } catch (EmptyResultDataAccessException _) {
            return Optional.empty();
        }
    }

    public List<Map<String, Object>> findAllByFk(String tableOrAlias, String fkDbColumn, Object fkValue) {
        TableMetadata t = registry.require(tableOrAlias);
        return jdbc.query(
                sqlBuilder.buildSelectByFk(t, fkDbColumn),
                new MapSqlParameterSource(FK_VALUE_PARAM, fkValue),
                new GenericRowMapper(t, converters));
    }
}
