package com.poc.transactions_consumer_canonical.repository;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.poc.transactions_consumer_canonical.mapper.SendTransactionRowMapper;
import com.poc.transactions_consumer_canonical.metadata.ColumnMetadata;
import com.poc.transactions_consumer_canonical.metadata.MetadataRegistry;
import com.poc.transactions_consumer_canonical.metadata.TableMetadata;
import com.poc.transactions_consumer_canonical.model.SendTransaction;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.Map;
import java.util.Optional;

/**
 * Metadata-driven implementation of {@link SendTransactionRepository}.
 *
 * <p>All SQL is generated by {@link SqlBuilder} from {@code send_transactions.yaml};
 * parameter binding iterates the same metadata and applies each column's
 * {@link ValueConverter} and JDBC type.
 *
 * <h3>Adding a new column</h3>
 * <ol>
 *   <li>Add the column in the table DDL.</li>
 *   <li>Add a row in {@code metadata/send_transactions.yaml}.</li>
 * </ol>
 * Nothing here needs to change — SELECT, MERGE, COUNT, and DELETE are all
 * regenerated from metadata at first use. (If you want to populate or read the
 * value, add the matching field on {@link SendTransaction} and the service-layer
 * request/response DTOs.)
 */
@Slf4j
@Repository
public class SendTransactionRepositoryImpl implements SendTransactionRepository {

    private static final String TABLE_NAME = "SEND_TRANSACTIONS";

    private final NamedParameterJdbcTemplate jdbc;
    private final SendTransactionRowMapper rowMapper;
    private final SqlBuilder sqlBuilder;
    private final Converters converters;
    private final ObjectMapper modelToMap;
    private final TableMetadata table;

    public SendTransactionRepositoryImpl(NamedParameterJdbcTemplate jdbc,
                                         SendTransactionRowMapper rowMapper,
                                         MetadataRegistry registry,
                                         SqlBuilder sqlBuilder,
                                         Converters converters,
                                         ObjectMapper jsonMapper) {
        this.jdbc = jdbc;
        this.rowMapper = rowMapper;
        this.sqlBuilder = sqlBuilder;
        this.converters = converters;
        this.table = registry.require(TABLE_NAME);
        // SendTransaction → Map<String,Object> via Jackson; values stay as java types
        // (BigDecimal, LocalDateTime, Boolean) so per-column converters work as designed.
        this.modelToMap = jsonMapper.copy();
        log.info("[SendTransactionRepositoryImpl] Metadata-driven; {} column(s) on {}",
                table.getColumns().size(), TABLE_NAME);
    }

    // ──────────────────────────────────────────────────────────
    // Write
    // ──────────────────────────────────────────────────────────

    @Override
    public void upsert(SendTransaction t) {
        log.debug("MERGE {} tranId={}", TABLE_NAME, t.getTranId());
        jdbc.update(sqlBuilder.buildMerge(table), toParams(t));
        log.debug("MERGE {} complete tranId={}", TABLE_NAME, t.getTranId());
    }

    // ──────────────────────────────────────────────────────────
    // Read
    // ──────────────────────────────────────────────────────────

    @Override
    public Optional<SendTransaction> findById(String tranId) {
        String pkJson = table.pkColumn().getJsonName();
        try {
            return Optional.ofNullable(
                    jdbc.queryForObject(sqlBuilder.buildSelectByPk(table),
                            new MapSqlParameterSource(pkJson, tranId), rowMapper));
        } catch (EmptyResultDataAccessException _) {
            return Optional.empty();
        }
    }

    // ──────────────────────────────────────────────────────────
    // Internal — metadata-driven parameter binding
    // ──────────────────────────────────────────────────────────

    /**
     * Converts the {@link SendTransaction} POJO into a {@code jsonName → value} map
     * (via Jackson, so {@code LocalDateTime}, {@code BigDecimal}, {@code Boolean}
     * stay as their native Java types) and binds each metadata column with its
     * declared JDBC type and converter.
     */
    private MapSqlParameterSource toParams(SendTransaction t) {
        @SuppressWarnings("unchecked")
        Map<String, Object> payload = modelToMap.convertValue(t, Map.class);

        MapSqlParameterSource params = new MapSqlParameterSource();
        for (ColumnMetadata col : table.getColumns()) {
            if (col.isAudit() || col.isReadOnly() || col.getJsonName() == null) continue;
            String key = col.getJsonName();
            Object raw = payload.get(key);
            Object jdbcValue = converters.forName(col.converterName()).toJdbc(raw, col);
            params.addValue(key, jdbcValue, col.jdbcType());
        }
        return params;
    }
}
